#:schema node_modules/wrangler/config-schema.json
name = "auth-adapter-app"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "next-auth-db"
database_id = "<unique-ID-for-your-database>"
migrations_dir = "./drizzle/migrations"
